# File : .pep8speaks.yml

scanner:
    diff_only: True  # If True, errors caused by only the patch are shown

pycodestyle:
    max-line-length: 79
    ignore:
        - E251, # unexpected spaces around keyword / parameter equals
        - E265, # block comment should start with '# '
        - E302, # expected 2 blank lines, found 1
        - E501, # line too long (105 > 79 characters)
        - F401, # '...' imported but unused
        - W292, # no newline at end of file
        - W293 # blank line contains whitespace
        